package enums;

public enum TransactionStatus {
    SUCCESS,
    FAILED_INSUFFICIENT_FUNDS,
    FAILED_INVALID_ACCOUNT,
    FAILED_MINIMUM_BALANCE_VIOLATION,
    FAILED_OVERDRAFT_EXCEEDED,
    FAILED_ACCOUNT_BLOCKED
}
